--CREATE AND USE DATABASE
CREATE DATABASE burgers_db;
USE burgers_db;

--CREATE TABLE
CREATE TABLE burgers(
    id INT NOT NULL AUTO_INCREMENT,
    burger_name VARCHAR(30) NOT NULL,
    is_favorite BOOLEAN,
    PRIMARY KEY(ID)
)